SRCS=GUIDialogControllerInput.cpp \
     GUIViewStateWindowGames.cpp \
     GUIWindowGameControllers.cpp \
     GUIWindowGames.cpp

LIB=gamewindows.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
