SRCS=GenericTouchActionHandler.cpp \
     GenericTouchButtonMapper.cpp \
     GenericTouchInputHandler.cpp \
     GenericTouchRotateDetector.cpp \

LIB=input_joysticks_generic.a

include ../../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
