SRCS=DigitalAnalogButtonConverter.cpp \
     GenericJoystickButtonMapping.cpp \
     GenericJoystickInputHandling.cpp \
     GenericJoystickKeyboardHandler.cpp \

LIB=input_joysticks_generic.a

include ../../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
