SRCS=BasicMemoryStream.cpp \
     DeltaPairMemoryStream.cpp \
     LinearMemoryStream.cpp \

LIB=gamesavestates.a

include ../../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
