SRCS=SteamLinkVideo.cpp \

LIB=steamlinkvideo.a

include ../../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

#ifeq (@USE_STEAMLINK@,1)
#SRCS += SteamLinkVideo.cpp
#endif
