SRCS=GameClient.cpp \
     GameClientProperties.cpp \
     GameController.cpp \
     GameControllerFeature.cpp \
     GameControllerLayout.cpp \

LIB=gameaddons.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
