SRCS=GameboyTag.cpp \
     GameInfoTag.cpp \
     GameInfoTagLoader.cpp \
     GBATag.cpp

LIB=gameinfotags.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
